### ISSUE TITLE
Works great.

### ISSUE THREAD

**Issue by averyfreeman** [jsimck/jsconfig.json#17]
People usually only post issues, but that can be a drag.  Wanted to report success and say thanks, worked great for my react project. 

I replaced a perfectly good working `jsconfig.json` just to try it out.  Didn't break anything, even with my absolute path `[baseUrl] = ./src` config.  Was slightly concerned about disparity of `webpack.config.json` being specified in `README.md`, but `webpack.config.js` appears to work fine. 

CRA command line opts (for reference):
```
npx jsconfig.json --baseUrl ./src --webpackConfigPath ./node_modules/react-scripts/config/webpack.config.js
```

**Comment by jsimck** [comment]
Hi, thank you for the feedback! It's always nice to hear that it works as expected for someone else too, rather than just me :).

Could you point me to direction where I mention `webpack.config.json`? It's definitely a mistake, should be a `webpack.config.js` for sure. But I couldn't find it anywhere in the current readme.
